# Build settings
markdown: kramdown
highlighter: rouge

# Site settings
title: "Celestine Omin"
description: > # this means to ignore newlines until "email:"
   On Software, life and everything in-between

email: celestineomin@gmail.com
#blog logo
logo: "/assets/images/author.jpg"
# blog cover
cover: "/assets/images/bg.png"

name: 'Celestine Omin'
author: 'Celestine Omin'
author_image: "/assets/images/author.jpg"

# permalink: /:categories/:title/

paginate:	5

url: "http://cyberomin.github.io" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/cyberomin
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/cyberomin
    desc:	Find me on GitHub
    share_url:
    share_title:
    share_link:

  - icon:	linkedin
    url:	https://ng.linkedin.com/in/celestineomin
    desc:	Find me on linkedin
    share_url:
    share_title:
    share_link:
